import './globals.css';
import { oswald, monte } from './components/Fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
	    <body className={`${monte.variable} ${oswald.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
