import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { createContext, useContext } from 'react';
import { initializeStore } from './stores/initializeStore.ts'

// Create the MobX store context
export const StoreContext = createContext(null);

// A hook for components to access the store easily
export const useStore = () => {
  const store = useContext(StoreContext);
  if (!store) {
    throw new Error('useStore must be used within a StoreProvider');
  }
  return store;
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, initialMobXState }: { children: React.ReactNode, initialMobXState?: any }) {
  // Hydrate stores with server-side data or initialize fresh
  const store = initializeStore(initialMobXState);

  return (
    <StoreContext.Provider value={store}>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </StoreContext.Provider>
  )
}
